/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: muckmuddy (https://sketchfab.com/muckmuddy)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/standard-mug-1ddf0e1fc752455b8bc78d0980436ea8
title: Standard Mug
*/

import React, {useRef} from 'react'
import {useGLTF, useTexture} from '@react-three/drei'
import {GroupProps} from "@react-three/fiber";

type Props = GroupProps & {
  image: string
}

export default function Mug({image, ...props}: Props) {

  const texture = useTexture(image)

  const group = useRef()
  const { nodes, materials }: any = useGLTF('/model1.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0, -4.28, 0]} rotation={[-Math.PI / 2, 0, Math.PI]} scale={15}>
            <mesh geometry={nodes.Plane002_Material_0.geometry} material={materials.Material} />
          </group>
          <group rotation={[-Math.PI / 2, 0, Math.PI]} scale={10}>
            <mesh geometry={nodes.Mug_Porcelain_PBR002_0.geometry} material={materials['Porcelain_PBR.002']} />
            <mesh geometry={nodes.Mug_Porcelain_PBR001_0.geometry} >
              <meshStandardMaterial map={texture}/>
            </mesh>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/model1.glb')
